# Generated by Django 5.1.2 on 2024-11-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_menuresto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='code',
            new_name='name',
        ),
    ]
