# Generated by Django 5.1.2 on 2024-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_rename_code_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuresto',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
