# Generated by Django 5.1.3 on 2024-11-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_alter_menuresto_image_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuresto',
            name='image_menu',
            field=models.ImageField(blank=True, default='/media/default_images/empty.jpg', null=True, upload_to='menu_images/'),
        ),
    ]
